### ISSUE TITLE
Extra Tracker Details

### ISSUE THREAD

**Issue by l-gorman** [JGIBristol/ask-jgi-handbook#19]
- [ ] Make sure "fill out hours" is clear 
- [ ] Remove zoom link for meetings (but mention hybrid option)
- [ ] Add notes on what to do if there is not an existing tag? (keep restricted/logged)
- [ ] Tags will be updated (query topic and task)
