### ISSUE TITLE
Away day meta-issue

### ISSUE THREAD

**Issue by jatonline** [JGIBristol/ask-jgi-handbook#25]
This issue contains a breakdown of what we want to achieve during our away day.

- [x] Update related services page - stats clinic, RSE, Research IT and other offerings from JGI, including seed corn funding - may need to go on a new page (write it so that it can be copied direct to an email) @WillGChapman 
- [x] Check the "Filling out the tracker" screenshots and whether they need to be updated @mgchandler 
- [x] Re-evaluate and document the categories of query in the handbook @richard-lane 
- [x] Recuitment page - Add to the list of where to advertise the service, make it clear that recruitment link is an annual thing, but encourage applications whenever @mvab 
- [x] Shift organisation and shift signup - update so still relevant for (at least) one person on shift (also see #21) @lippirk 
- [x] "Weekly meetings" page - update links and make relevant to current meeting format, hybrid, locations, etc. @vairylein 
- [x] Roadshow (also see #24) @NatalieZelenka 
- [x] Where to store things - SharePoint or GitHub (and ackowledge Ask-JGI service) (also see #17) @jatonline 

---

- [ ] Who needs to make rooms booking, calendar invites, etc.
- [ ] Update contributors list in README
- [ ] Examples of queries
- [ ] "Claiming payment" page - add screenshot of timesheet, update details, 2h for being on shift, round up to nearest 0.25h, etc.
